title: OwlSec | Web Development & Graphic Design
baseURL: /
params:
  description: >-
    Welcome to OwlSec, the strategic  I.T company leading the frontier in this
    digital age.
  layout: full-width
  style: classic
  palette: green
  mode: light
  base_font: serif
  header:
    type: header
    template: header
    title: OwlSec Co
    logo: /images/gradient icon logo.png
    has_primary_nav: true
    primary_nav_links:
      - type: action
        template: action
        label: About
        url: /about
        style: link
      - type: action
        template: action
        label: Services
        url: /features
        style: link
      - type: action
        template: action
        label: Pricing
        url: /pricing
        style: link
      - type: action
        template: action
        label: Blog
        url: /blog
        style: link
    has_secondary_nav: true
    secondary_nav_links:
      - type: action
        template: action
        label: Contact
        url: /contact
        style: link
      - type: action
        template: action
        label: Get Started
        url: /pricing
        style: primary
    has_anncmnt: true
    anncmnt_content: >-
      Gain a free 1 year .co.ke domain name by buying our bronze webmail package
      at only ksh. 1000.
    anncmnt_align: left
    anncmnt_is_home_only: true
    anncmnt_has_close: true
    anncmnt_id: new-features
  footer:
    type: footer
    template: footer
    logo: /images/cover.png
    has_primary_nav: true
    primary_nav_title: Company
    primary_nav_links:
      - type: action
        template: action
        label: About
        url: /about
        style: link
      - label: Services
        url: /services
        style: link
        has_icon: false
        icon: arrow-left
        icon_position: right
        new_window: false
        type: action
      - label: Case Studies
        url: lorem-ipsum
        style: link
        has_icon: false
        icon: arrow-left
        icon_position: right
        new_window: false
        type: action
    has_secondary_nav: true
    secondary_nav_title: Blog
    secondary_nav_links:
      - type: action
        template: action
        label: News
        url: /blog/category/news
        style: link
      - type: action
        template: action
        label: General
        url: /blog/category/general
        style: link
      - type: action
        template: action
        label: Tutorials
        url: /blog/category/tutorials
        style: link
    has_tertiary_nav: true
    tertiary_nav_title: Legal
    tertiary_nav_links:
      - type: action
        template: action
        label: Terms & Conditions
        url: /terms-conditions
        style: link
      - type: action
        template: action
        label: Privacy Policy
        url: /privacy-policy
        style: link
    has_social: true
    social_links:
      - type: action
        template: action
        label: OwlSec is on Twitter
        url: 'https://twitter.com/owlsec_co'
        style: link
        has_icon: true
        icon: twitter
        icon_position: center
        new_window: true
      - type: action
        template: action
        label: OwlSec is on GitHub
        url: 'https://github.com/owlsecco'
        style: link
        has_icon: true
        icon: github
        icon_position: center
        new_window: true
      - type: action
        template: action
        label: OwlSec is on LinkedIn
        url: 'https://www.linkedin.com/company/owlsecco'
        style: link
        has_icon: true
        icon: linkedin
        icon_position: center
        new_window: true
    content: >-
      &copy; OwlSec Co. All rights reserved. This is a JAMStack site created on
      <a href="https://www.stackbit.com" target="_blank"
      rel="noopener">Stackbit</a>.
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
